version: "3.8"

networks:
  net:
    driver: bridge

services:

  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'chatbot'
    ports:
      - 9191:9191
    networks:
      - net
    depends_on:
      - mongo
      - chroma

  mongo:
    image: 'mongo:7.0.8'
    container_name: 'mongodb'
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=gamefichatbot
    networks:
      - net
#--------------------------------------------------------
  chroma:
    image: chromadb/chroma:0.5.2.dev9
    volumes:
      - chroma-data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma # this is the default path, change it as needed
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
    ports:
      - 8000:8000
    networks:
      - net

# -------------------------------------


volumes:
  mongo-data:
  mongo-config:
  chroma-data: