version: '3.8'

services:
  chatbot:
    build: 
      dockerfile: Dockerfile
    container_name: chatbot
    restart: always
    volumes:
      - db:/code/db
      - data:/code/data
      - .env:/code/.env
    ports:
      - "8080:8080"
      - "9191:9191"
    command: python /code/app/app.py
    network_mode: host
volumes:
  db:
    driver: local
  data:
    driver: local
  .env:
    driver: local